apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-consul-consul-server-0
  namespace: consul
  labels:
    app: consul
    release: consul
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  selector:
    matchLabels:
      app: consul
