apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-pv
  labels:
    app: consul
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  hostPath:
    path: "/opt/data"
