kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik-ingress-controller
          image: traefik:v2.11.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - name: traefik-config
              mountPath: /etc/traefik/traefik.toml
              subPath: traefik.toml
      volumes:
        - name: traefik-config
          configMap:
            name: traefik-config
        - name: traefik-config-dynamic
          configMap:
            name: traefik-config-dynamic
