# 为traefik服务创建service, 为外部开放使用
apiVersion: v1
kind: Service
metadata:
  name: traefik-svc
  namespace: traefik
spec:
  selector:
    app: traefik
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30080
    - name: https
      port: 443
      nodePort: 30443
    - name: dashboard
      port: 8080
      nodePort: 32080